"""Built-in language pack: consent UI, purposes and gate texts.

Service descriptions for catalog services exist in en/de/es (catalog.py); other
languages start from English and are edited in the generator.
"""

RTL_LANGUAGES = ["ar", "arc", "ckb", "dv", "fa", "he", "ku", "ps", "sd", "ug", "ur", "yi"]


def lang_pack(name, dir_, privacy_label, notice, modal, consent_manager, purposes, gate):
    return {
        "name": name,
        "dir": dir_,
        "privacyLabel": privacy_label,
        "notice": dict(zip(["title", "text", "changes", "customize", "decline", "accept"], notice)),
        "modal": dict(zip(["title", "text", "close", "toggleAll", "alwaysActive", "activeByDefault", "service", "services", "decline", "save", "accept"], modal)),
        "consentManager": dict(zip(["title", "description"], consent_manager)),
        "purposes": {key: list(value) for key, value in zip(["essential", "analytics", "marketing", "media", "functional"], purposes)},
        "gate": dict(zip(["load", "always", "settings", "text", "cancel"], gate)),
    }


LANGUAGES = {
    "en": lang_pack(
        "English", "ltr", "privacy policy",
        ["We value your privacy",
         "We use cookies and similar technologies for essential functions and, with your consent, for analytics, marketing and embedded media. You can change your choice at any time. Learn more in our",
         "Our services have changed since your last visit. Please review your choice.",
         "Customize", "Decline all", "Accept all"],
        ["Privacy settings",
         "Choose which services we may use. Essential services are always active. You can change your choice at any time. Learn more in our",
         "Close privacy settings", "Enable or disable all services", "Always active", "Active by default", "service", "services",
         "Decline all", "Save selection", "Accept all"],
        ["Consent manager", "Stores your privacy choices in the cmp_consent cookie."],
        [("Essential", "Required for the website to work, for example to remember your privacy choices."),
         ("Analytics", "Help us understand how visitors use the website so we can improve it."),
         ("Marketing", "Measure the performance of our advertising and show more relevant ads."),
         ("External media", "Load content from third-party platforms such as videos, maps and social posts."),
         ("Functional", "Enable features such as live chat, scheduling and spam protection.")],
        ["Load content", "Always allow {provider}", "Privacy settings",
         "This content is provided by {provider}. Loading it may set cookies and transfer data to {provider}.", "Cancel"],
    ),
    "de": lang_pack(
        "Deutsch", "ltr", "Datenschutzerklärung",
        ["Ihre Privatsphäre ist uns wichtig",
         "Wir verwenden Cookies und ähnliche Technologien für notwendige Funktionen und, mit Ihrer Einwilligung, für Statistik, Marketing und eingebettete Medien. Sie können Ihre Auswahl jederzeit ändern. Mehr dazu in unserer",
         "Unsere Dienste haben sich seit Ihrem letzten Besuch geändert. Bitte prüfen Sie Ihre Auswahl.",
         "Anpassen", "Alle ablehnen", "Alle akzeptieren"],
        ["Datenschutz-Einstellungen",
         "Wählen Sie, welche Dienste wir nutzen dürfen. Essenzielle Dienste sind immer aktiv. Sie können Ihre Auswahl jederzeit ändern. Mehr dazu in unserer",
         "Datenschutz-Einstellungen schließen", "Alle Dienste aktivieren oder deaktivieren", "Immer aktiv", "Standardmäßig aktiv", "Dienst", "Dienste",
         "Alle ablehnen", "Auswahl speichern", "Alle akzeptieren"],
        ["Consent-Manager", "Speichert Ihre Auswahl im Cookie cmp_consent."],
        [("Essenziell", "Für den Betrieb der Website erforderlich, zum Beispiel um Ihre Datenschutz-Auswahl zu speichern."),
         ("Statistik", "Helfen uns zu verstehen, wie Besucher die Website nutzen, damit wir sie verbessern können."),
         ("Marketing", "Messen den Erfolg unserer Werbung und zeigen relevantere Anzeigen."),
         ("Externe Medien", "Laden Inhalte von Drittanbietern wie Videos, Karten und Social-Media-Beiträge."),
         ("Funktional", "Ermöglichen Funktionen wie Live-Chat, Terminbuchung und Spam-Schutz.")],
        ["Inhalt laden", "{provider} immer erlauben", "Datenschutz-Einstellungen",
         "Dieser Inhalt wird von {provider} bereitgestellt. Beim Laden können Cookies gesetzt und Daten an {provider} übertragen werden.", "Abbrechen"],
    ),
    "es": lang_pack(
        "Español", "ltr", "política de privacidad",
        ["Tu privacidad nos importa",
         "Usamos cookies y tecnologías similares para funciones esenciales y, con tu consentimiento, para analítica, marketing y contenido incrustado. Puedes cambiar tu elección en cualquier momento. Más información en nuestra",
         "Nuestros servicios han cambiado desde tu última visita. Revisa tu elección.",
         "Personalizar", "Rechazar todo", "Aceptar todo"],
        ["Configuración de privacidad",
         "Elige qué servicios podemos usar. Los servicios esenciales están siempre activos. Puedes cambiar tu elección en cualquier momento. Más información en nuestra",
         "Cerrar la configuración de privacidad", "Activar o desactivar todos los servicios", "Siempre activo", "Activo por defecto", "servicio", "servicios",
         "Rechazar todo", "Guardar selección", "Aceptar todo"],
        ["Gestor de consentimiento", "Guarda tu elección en la cookie cmp_consent."],
        [("Esenciales", "Necesarios para que el sitio web funcione, por ejemplo para recordar tu elección de privacidad."),
         ("Analítica", "Nos ayudan a entender cómo se usa el sitio web para poder mejorarlo."),
         ("Marketing", "Miden el rendimiento de nuestra publicidad y muestran anuncios más relevantes."),
         ("Contenido externo", "Cargan contenido de plataformas de terceros, como vídeos, mapas y publicaciones."),
         ("Funcionales", "Permiten funciones como chat en vivo, reservas y protección contra spam.")],
        ["Cargar contenido", "Permitir siempre {provider}", "Configuración de privacidad",
         "Este contenido lo proporciona {provider}. Al cargarlo, se pueden instalar cookies y transmitir datos a {provider}.", "Cancelar"],
    ),
    "fr": lang_pack(
        "Français", "ltr", "politique de confidentialité",
        ["Nous respectons votre vie privée",
         "Nous utilisons des cookies et des technologies similaires pour les fonctions essentielles et, avec votre consentement, pour les statistiques, le marketing et les contenus intégrés. Vous pouvez modifier votre choix à tout moment. Pour en savoir plus, consultez notre",
         "Nos services ont changé depuis votre dernière visite. Veuillez vérifier votre choix.",
         "Personnaliser", "Tout refuser", "Tout accepter"],
        ["Paramètres de confidentialité",
         "Choisissez les services que nous pouvons utiliser. Les services essentiels sont toujours actifs. Vous pouvez modifier votre choix à tout moment. Pour en savoir plus, consultez notre",
         "Fermer les paramètres de confidentialité", "Activer ou désactiver tous les services", "Toujours actif", "Actif par défaut", "service", "services",
         "Tout refuser", "Enregistrer la sélection", "Tout accepter"],
        ["Gestionnaire de consentement", "Enregistre vos choix de confidentialité dans le cookie cmp_consent."],
        [("Essentiels", "Nécessaires au fonctionnement du site, par exemple pour mémoriser vos choix de confidentialité."),
         ("Statistiques", "Nous aident à comprendre comment les visiteurs utilisent le site afin de l’améliorer."),
         ("Marketing", "Mesurent l’efficacité de nos publicités et affichent des annonces plus pertinentes."),
         ("Médias externes", "Chargent des contenus de plateformes tierces, comme des vidéos, des cartes et des publications."),
         ("Fonctionnels", "Permettent des fonctions comme le chat en direct, la prise de rendez-vous et la protection contre le spam.")],
        ["Charger le contenu", "Toujours autoriser {provider}", "Paramètres de confidentialité",
         "Ce contenu est fourni par {provider}. Son chargement peut déposer des cookies et transmettre des données à {provider}.", "Annuler"],
    ),
    "it": lang_pack(
        "Italiano", "ltr", "informativa sulla privacy",
        ["Rispettiamo la tua privacy",
         "Utilizziamo cookie e tecnologie simili per le funzioni essenziali e, con il tuo consenso, per statistiche, marketing e contenuti incorporati. Puoi modificare la tua scelta in qualsiasi momento. Maggiori informazioni nella nostra",
         "I nostri servizi sono cambiati dalla tua ultima visita. Controlla la tua scelta.",
         "Personalizza", "Rifiuta tutto", "Accetta tutto"],
        ["Impostazioni privacy",
         "Scegli quali servizi possiamo utilizzare. I servizi essenziali sono sempre attivi. Puoi modificare la tua scelta in qualsiasi momento. Maggiori informazioni nella nostra",
         "Chiudi le impostazioni privacy", "Attiva o disattiva tutti i servizi", "Sempre attivo", "Attivo per impostazione predefinita", "servizio", "servizi",
         "Rifiuta tutto", "Salva selezione", "Accetta tutto"],
        ["Gestore del consenso", "Memorizza le tue scelte sulla privacy nel cookie cmp_consent."],
        [("Essenziali", "Necessari per il funzionamento del sito, ad esempio per ricordare le tue scelte sulla privacy."),
         ("Statistiche", "Ci aiutano a capire come i visitatori usano il sito per migliorarlo."),
         ("Marketing", "Misurano l’efficacia della nostra pubblicità e mostrano annunci più pertinenti."),
         ("Contenuti esterni", "Caricano contenuti da piattaforme di terze parti come video, mappe e post."),
         ("Funzionali", "Abilitano funzioni come chat dal vivo, prenotazioni e protezione dallo spam.")],
        ["Carica contenuto", "Consenti sempre {provider}", "Impostazioni privacy",
         "Questo contenuto è fornito da {provider}. Caricandolo potrebbero essere impostati cookie e trasmessi dati a {provider}.", "Annulla"],
    ),
    "pt": lang_pack(
        "Português", "ltr", "política de privacidade",
        ["Respeitamos a sua privacidade",
         "Utilizamos cookies e tecnologias semelhantes para funções essenciais e, com o seu consentimento, para estatísticas, marketing e conteúdos incorporados. Pode alterar a sua escolha a qualquer momento. Saiba mais na nossa",
         "Os nossos serviços mudaram desde a sua última visita. Reveja a sua escolha.",
         "Personalizar", "Rejeitar tudo", "Aceitar tudo"],
        ["Definições de privacidade",
         "Escolha os serviços que podemos utilizar. Os serviços essenciais estão sempre ativos. Pode alterar a sua escolha a qualquer momento. Saiba mais na nossa",
         "Fechar definições de privacidade", "Ativar ou desativar todos os serviços", "Sempre ativo", "Ativo por predefinição", "serviço", "serviços",
         "Rejeitar tudo", "Guardar seleção", "Aceitar tudo"],
        ["Gestor de consentimento", "Guarda as suas escolhas de privacidade no cookie cmp_consent."],
        [("Essenciais", "Necessários para o funcionamento do site, por exemplo para guardar as suas escolhas de privacidade."),
         ("Estatísticas", "Ajudam-nos a perceber como os visitantes utilizam o site para o podermos melhorar."),
         ("Marketing", "Medem o desempenho da nossa publicidade e mostram anúncios mais relevantes."),
         ("Conteúdos externos", "Carregam conteúdos de plataformas de terceiros, como vídeos, mapas e publicações."),
         ("Funcionais", "Permitem funções como chat ao vivo, marcações e proteção contra spam.")],
        ["Carregar conteúdo", "Permitir sempre {provider}", "Definições de privacidade",
         "Este conteúdo é fornecido por {provider}. Ao carregá-lo, podem ser definidos cookies e transmitidos dados para {provider}.", "Cancelar"],
    ),
    "nl": lang_pack(
        "Nederlands", "ltr", "privacyverklaring",
        ["Wij respecteren je privacy",
         "We gebruiken cookies en vergelijkbare technieken voor essentiële functies en, met je toestemming, voor statistieken, marketing en ingesloten media. Je kunt je keuze altijd wijzigen. Lees meer in onze",
         "Onze diensten zijn gewijzigd sinds je laatste bezoek. Controleer je keuze.",
         "Aanpassen", "Alles weigeren", "Alles accepteren"],
        ["Privacyinstellingen",
         "Kies welke diensten we mogen gebruiken. Essentiële diensten zijn altijd actief. Je kunt je keuze altijd wijzigen. Lees meer in onze",
         "Privacyinstellingen sluiten", "Alle diensten in- of uitschakelen", "Altijd actief", "Standaard actief", "dienst", "diensten",
         "Alles weigeren", "Selectie opslaan", "Alles accepteren"],
        ["Toestemmingsbeheer", "Slaat je privacykeuzes op in de cookie cmp_consent."],
        [("Essentieel", "Nodig om de website te laten werken, bijvoorbeeld om je privacykeuzes te onthouden."),
         ("Statistieken", "Helpen ons begrijpen hoe bezoekers de website gebruiken, zodat we die kunnen verbeteren."),
         ("Marketing", "Meten de prestaties van onze advertenties en tonen relevantere advertenties."),
         ("Externe media", "Laden inhoud van externe platforms, zoals video’s, kaarten en berichten."),
         ("Functioneel", "Maken functies mogelijk zoals livechat, afspraken plannen en spambescherming.")],
        ["Inhoud laden", "{provider} altijd toestaan", "Privacyinstellingen",
         "Deze inhoud wordt geleverd door {provider}. Bij het laden kunnen cookies worden geplaatst en gegevens naar {provider} worden verzonden.", "Annuleren"],
    ),
    "pl": lang_pack(
        "Polski", "ltr", "polityce prywatności",
        ["Szanujemy Twoją prywatność",
         "Używamy plików cookie i podobnych technologii do działania niezbędnych funkcji oraz, za Twoją zgodą, do statystyk, marketingu i osadzonych treści. Swój wybór możesz zmienić w każdej chwili. Więcej informacji w naszej",
         "Nasze usługi zmieniły się od Twojej ostatniej wizyty. Sprawdź swój wybór.",
         "Dostosuj", "Odrzuć wszystkie", "Akceptuj wszystkie"],
        ["Ustawienia prywatności",
         "Wybierz, z jakich usług możemy korzystać. Usługi niezbędne są zawsze aktywne. Swój wybór możesz zmienić w każdej chwili. Więcej informacji w naszej",
         "Zamknij ustawienia prywatności", "Włącz lub wyłącz wszystkie usługi", "Zawsze aktywne", "Domyślnie aktywne", "usługa", "usługi",
         "Odrzuć wszystkie", "Zapisz wybór", "Akceptuj wszystkie"],
        ["Menedżer zgód", "Zapisuje Twoje wybory dotyczące prywatności w pliku cookie cmp_consent."],
        [("Niezbędne", "Wymagane do działania strony, na przykład do zapamiętania Twoich wyborów dotyczących prywatności."),
         ("Statystyka", "Pomagają nam zrozumieć, jak odwiedzający korzystają ze strony, abyśmy mogli ją ulepszać."),
         ("Marketing", "Mierzą skuteczność naszych reklam i wyświetlają trafniejsze reklamy."),
         ("Treści zewnętrzne", "Wczytują treści z platform zewnętrznych, takie jak filmy, mapy i posty."),
         ("Funkcjonalne", "Umożliwiają funkcje takie jak czat na żywo, rezerwacje i ochrona przed spamem.")],
        ["Wczytaj treść", "Zawsze zezwalaj: {provider}", "Ustawienia prywatności",
         "Ta treść jest dostarczana przez {provider}. Jej wczytanie może zapisać pliki cookie i przekazać dane do {provider}.", "Anuluj"],
    ),
    "ar": lang_pack(
        "العربية", "rtl", "سياسة الخصوصية",
        ["نحن نحترم خصوصيتك",
         "نستخدم ملفات تعريف الارتباط والتقنيات المشابهة للوظائف الأساسية، وبموافقتك للإحصاءات والتسويق والمحتوى المضمّن. يمكنك تغيير اختيارك في أي وقت. لمعرفة المزيد، اطّلع على",
         "تغيّرت خدماتنا منذ زيارتك الأخيرة. يُرجى مراجعة اختيارك.",
         "تخصيص", "رفض الكل", "قبول الكل"],
        ["إعدادات الخصوصية",
         "اختر الخدمات التي يمكننا استخدامها. الخدمات الأساسية مفعّلة دائمًا. يمكنك تغيير اختيارك في أي وقت. لمعرفة المزيد، اطّلع على",
         "إغلاق إعدادات الخصوصية", "تفعيل جميع الخدمات أو تعطيلها", "مفعّل دائمًا", "مفعّل افتراضيًا", "خدمة", "خدمات",
         "رفض الكل", "حفظ الاختيار", "قبول الكل"],
        ["مدير الموافقة", "يحفظ اختيارات الخصوصية الخاصة بك في ملف تعريف الارتباط cmp_consent."],
        [("أساسية", "ضرورية لعمل الموقع، مثل تذكّر اختيارات الخصوصية الخاصة بك."),
         ("الإحصاءات", "تساعدنا على فهم كيفية استخدام الزوار للموقع لتحسينه."),
         ("التسويق", "تقيس أداء إعلاناتنا وتعرض إعلانات أكثر ملاءمة."),
         ("الوسائط الخارجية", "تحمّل محتوى من منصات خارجية مثل مقاطع الفيديو والخرائط والمنشورات."),
         ("وظيفية", "تتيح ميزات مثل الدردشة المباشرة وحجز المواعيد والحماية من الرسائل المزعجة.")],
        ["تحميل المحتوى", "السماح دائمًا بـ {provider}", "إعدادات الخصوصية",
         "يُقدَّم هذا المحتوى من {provider}. قد يؤدي تحميله إلى حفظ ملفات تعريف الارتباط ونقل البيانات إلى {provider}.", "إلغاء"],
    ),
    "he": lang_pack(
        "עברית", "rtl", "מדיניות הפרטיות",
        ["אנחנו מכבדים את הפרטיות שלך",
         "אנחנו משתמשים בעוגיות ובטכנולוגיות דומות לפונקציות חיוניות, ובהסכמתך גם לסטטיסטיקה, לשיווק ולתוכן מוטמע. אפשר לשנות את הבחירה בכל עת. למידע נוסף ראו את",
         "השירותים שלנו השתנו מאז הביקור האחרון שלך. יש לבדוק את הבחירה.",
         "התאמה אישית", "דחיית הכול", "אישור הכול"],
        ["הגדרות פרטיות",
         "בחרו באילו שירותים נוכל להשתמש. שירותים חיוניים פעילים תמיד. אפשר לשנות את הבחירה בכל עת. למידע נוסף ראו את",
         "סגירת הגדרות הפרטיות", "הפעלה או השבתה של כל השירותים", "פעיל תמיד", "פעיל כברירת מחדל", "שירות", "שירותים",
         "דחיית הכול", "שמירת הבחירה", "אישור הכול"],
        ["ניהול הסכמה", "שומר את בחירות הפרטיות שלך בעוגייה cmp_consent."],
        [("חיוניים", "נדרשים לפעולת האתר, למשל כדי לזכור את בחירות הפרטיות שלך."),
         ("סטטיסטיקה", "עוזרים לנו להבין איך מבקרים משתמשים באתר כדי לשפר אותו."),
         ("שיווק", "מודדים את ביצועי הפרסום שלנו ומציגים מודעות רלוונטיות יותר."),
         ("מדיה חיצונית", "טוענים תוכן מפלטפורמות חיצוניות כמו סרטונים, מפות ופוסטים."),
         ("פונקציונליים", "מאפשרים תכונות כמו צ׳אט חי, קביעת פגישות והגנה מפני ספאם.")],
        ["טעינת התוכן", "לאפשר תמיד את {provider}", "הגדרות פרטיות",
         "התוכן הזה מסופק על ידי {provider}. טעינתו עשויה לשמור עוגיות ולהעביר נתונים אל {provider}.", "ביטול"],
    ),
}

ORDER = ["en", "de", "es", "fr", "it", "pt", "nl", "pl", "ar", "he"]


def text_direction(code):
    return "rtl" if code.split("-")[0].lower() in RTL_LANGUAGES else "ltr"
