"""Catalog service descriptions for fr, it, pt, nl, pl, ar and he (en/de/es live in catalog.py)."""

DESCRIPTIONS = {
    "google-analytics": {
        "fr": "Collecte des statistiques d’utilisation pseudonymisées.",
        "it": "Raccoglie statistiche di utilizzo pseudonimizzate.",
        "pt": "Recolhe estatísticas de utilização pseudonimizadas.",
        "nl": "Verzamelt gepseudonimiseerde gebruiksstatistieken.",
        "pl": "Zbiera pseudonimizowane statystyki korzystania.",
        "ar": "يجمع إحصاءات استخدام مستعارة الهوية.",
        "he": "אוסף סטטיסטיקות שימוש בזהות בדויה.",
    },
    "matomo": {
        "fr": "Collecte des statistiques de visite pseudonymisées.",
        "it": "Raccoglie statistiche sui visitatori pseudonimizzate.",
        "pt": "Recolhe estatísticas de visitantes pseudonimizadas.",
        "nl": "Verzamelt gepseudonimiseerde bezoekersstatistieken.",
        "pl": "Zbiera pseudonimizowane statystyki odwiedzin.",
        "ar": "يجمع إحصاءات زوار مستعارة الهوية.",
        "he": "אוסף סטטיסטיקות מבקרים בזהות בדויה.",
    },
    "plausible": {
        "fr": "Statistiques de site sans cookies et respectueuses de la vie privée.",
        "it": "Statistiche del sito senza cookie e rispettose della privacy.",
        "pt": "Estatísticas do site sem cookies e respeitadoras da privacidade.",
        "nl": "Cookieloze, privacyvriendelijke websitestatistieken.",
        "pl": "Statystyki strony bez plików cookie, przyjazne dla prywatności.",
        "ar": "إحصاءات للموقع بلا ملفات تعريف ارتباط وتحترم الخصوصية.",
        "he": "סטטיסטיקות אתר ללא עוגיות, ששומרות על הפרטיות.",
    },
    "rybbit": {
        "fr": "Analyse web et produit sans cookies, respectueuse de la vie privée.",
        "it": "Analisi web e di prodotto senza cookie, rispettosa della privacy.",
        "pt": "Análise web e de produto sem cookies e respeitadora da privacidade.",
        "nl": "Cookieloze, privacyvriendelijke web- en productanalyse.",
        "pl": "Analityka stron i produktów bez plików cookie, przyjazna dla prywatności.",
        "ar": "تحليلات للموقع والمنتج بلا ملفات تعريف ارتباط وتحترم الخصوصية.",
        "he": "ניתוח אתרים ומוצרים ללא עוגיות, ששומר על הפרטיות.",
    },
    "microsoft-clarity": {
        "fr": "Enregistrements de sessions et cartes de chaleur pour améliorer l’ergonomie.",
        "it": "Registrazioni delle sessioni e mappe di calore per migliorare l’usabilità.",
        "pt": "Gravações de sessões e mapas de calor para melhorar a usabilidade.",
        "nl": "Sessie-opnames en heatmaps om de gebruiksvriendelijkheid te verbeteren.",
        "pl": "Nagrania sesji i mapy cieplne pomagające poprawić użyteczność.",
        "ar": "تسجيلات للجلسات وخرائط حرارية لتحسين سهولة الاستخدام.",
        "he": "הקלטות של ביקורים ומפות חום לשיפור השימושיות.",
    },
    "hotjar": {
        "fr": "Cartes de chaleur, enregistrements et questionnaires de satisfaction.",
        "it": "Mappe di calore, registrazioni e sondaggi di feedback.",
        "pt": "Mapas de calor, gravações e inquéritos de opinião.",
        "nl": "Heatmaps, opnames en feedbackenquêtes.",
        "pl": "Mapy cieplne, nagrania i ankiety opinii.",
        "ar": "خرائط حرارية وتسجيلات واستطلاعات للآراء.",
        "he": "מפות חום, הקלטות וסקרי משוב.",
    },
    "google-tag-manager": {
        "fr": "Charge les balises marketing et statistiques configurées dans Google Tag Manager.",
        "it": "Carica i tag di marketing e statistica configurati in Google Tag Manager.",
        "pt": "Carrega etiquetas de marketing e estatística configuradas no Google Tag Manager.",
        "nl": "Laadt marketing- en statistiektags die in Google Tag Manager zijn ingesteld.",
        "pl": "Wczytuje tagi marketingowe i analityczne skonfigurowane w Google Tag Manager.",
        "ar": "يحمّل وسوم التسويق والإحصاءات المُعدّة في Google Tag Manager.",
        "he": "טוען תגי שיווק וסטטיסטיקה שהוגדרו ב־Google Tag Manager.",
    },
    "google-ads": {
        "fr": "Mesure les conversions des campagnes Google Ads et permet le remarketing.",
        "it": "Misura le conversioni delle campagne Google Ads e consente il remarketing.",
        "pt": "Mede as conversões das campanhas do Google Ads e permite o remarketing.",
        "nl": "Meet conversies uit Google Ads-campagnes en maakt remarketing mogelijk.",
        "pl": "Mierzy konwersje z kampanii Google Ads i umożliwia remarketing.",
        "ar": "يقيس التحويلات من حملات Google Ads ويتيح إعادة التسويق.",
        "he": "מודד המרות מקמפיינים ב־Google Ads ומאפשר רימרקטינג.",
    },
    "meta-pixel": {
        "fr": "Mesure l’efficacité des publicités sur Facebook et Instagram.",
        "it": "Misura l’efficacia degli annunci su Facebook e Instagram.",
        "pt": "Mede a eficácia dos anúncios no Facebook e no Instagram.",
        "nl": "Meet de effectiviteit van advertenties op Facebook en Instagram.",
        "pl": "Mierzy skuteczność reklam na Facebooku i Instagramie.",
        "ar": "يقيس فعالية الإعلانات على فيسبوك وإنستغرام.",
        "he": "מודד את האפקטיביות של מודעות בפייסבוק ובאינסטגרם.",
    },
    "linkedin-insight": {
        "fr": "Suivi des conversions et reciblage pour les publicités LinkedIn.",
        "it": "Monitoraggio delle conversioni e retargeting per gli annunci LinkedIn.",
        "pt": "Acompanhamento de conversões e retargeting para anúncios do LinkedIn.",
        "nl": "Conversietracking en retargeting voor LinkedIn-advertenties.",
        "pl": "Śledzenie konwersji i retargeting dla reklam na LinkedIn.",
        "ar": "تتبّع التحويلات وإعادة الاستهداف لإعلانات LinkedIn.",
        "he": "מעקב המרות ורימרקטינג למודעות LinkedIn.",
    },
    "tiktok-pixel": {
        "fr": "Mesure les performances des campagnes publicitaires TikTok.",
        "it": "Misura il rendimento delle campagne pubblicitarie su TikTok.",
        "pt": "Mede o desempenho das campanhas publicitárias no TikTok.",
        "nl": "Meet de prestaties van TikTok-advertentiecampagnes.",
        "pl": "Mierzy skuteczność kampanii reklamowych na TikToku.",
        "ar": "يقيس أداء الحملات الإعلانية على TikTok.",
        "he": "מודד את הביצועים של קמפיינים פרסומיים ב־TikTok.",
    },
    "pinterest-tag": {
        "fr": "Suivi des conversions et audiences pour les publicités Pinterest.",
        "it": "Monitoraggio delle conversioni e segmenti di pubblico per gli annunci Pinterest.",
        "pt": "Acompanhamento de conversões e públicos para anúncios do Pinterest.",
        "nl": "Conversietracking en doelgroepen voor Pinterest-advertenties.",
        "pl": "Śledzenie konwersji i grupy odbiorców dla reklam na Pintereście.",
        "ar": "تتبّع التحويلات والجماهير لإعلانات Pinterest.",
        "he": "מעקב המרות וקהלים למודעות Pinterest.",
    },
    "youtube": {
        "fr": "Lit les vidéos intégrées. YouTube peut déposer des cookies lors du chargement d’une vidéo.",
        "it": "Riproduce video incorporati. YouTube può impostare cookie al caricamento di un video.",
        "pt": "Reproduz vídeos incorporados. O YouTube pode definir cookies quando um vídeo é carregado.",
        "nl": "Speelt ingesloten video’s af. YouTube kan cookies plaatsen zodra een video laadt.",
        "pl": "Odtwarza osadzone filmy. YouTube może zapisywać pliki cookie po wczytaniu filmu.",
        "ar": "يشغّل مقاطع الفيديو المضمّنة. قد يحفظ يوتيوب ملفات تعريف الارتباط عند تحميل الفيديو.",
        "he": "מפעיל סרטונים מוטמעים. YouTube עשוי לשמור עוגיות כשסרטון נטען.",
    },
    "vimeo": {
        "fr": "Lit les vidéos intégrées hébergées sur Vimeo.",
        "it": "Riproduce video incorporati ospitati su Vimeo.",
        "pt": "Reproduz vídeos incorporados alojados no Vimeo.",
        "nl": "Speelt ingesloten video’s van Vimeo af.",
        "pl": "Odtwarza osadzone filmy z serwisu Vimeo.",
        "ar": "يشغّل مقاطع الفيديو المضمّنة المستضافة على Vimeo.",
        "he": "מפעיל סרטונים מוטמעים שמאוחסנים ב־Vimeo.",
    },
    "google-maps": {
        "fr": "Affiche des cartes interactives.",
        "it": "Mostra mappe interattive.",
        "pt": "Mostra mapas interativos.",
        "nl": "Toont interactieve kaarten.",
        "pl": "Wyświetla interaktywne mapy.",
        "ar": "يعرض خرائط تفاعلية.",
        "he": "מציג מפות אינטראקטיביות.",
    },
    "spotify": {
        "fr": "Lit les titres, albums et podcasts intégrés.",
        "it": "Riproduce brani, album e podcast incorporati.",
        "pt": "Reproduz faixas, álbuns e podcasts incorporados.",
        "nl": "Speelt ingesloten nummers, albums en podcasts af.",
        "pl": "Odtwarza osadzone utwory, albumy i podcasty.",
        "ar": "يشغّل المقاطع والألبومات والبودكاست المضمّنة.",
        "he": "מפעיל שירים, אלבומים ופודקאסטים מוטמעים.",
    },
    "instagram": {
        "fr": "Affiche des publications Instagram intégrées.",
        "it": "Mostra post di Instagram incorporati.",
        "pt": "Mostra publicações do Instagram incorporadas.",
        "nl": "Toont ingesloten Instagram-berichten.",
        "pl": "Wyświetla osadzone posty z Instagrama.",
        "ar": "يعرض منشورات إنستغرام المضمّنة.",
        "he": "מציג פוסטים מוטמעים מאינסטגרם.",
    },
    "google-fonts": {
        "fr": "Charge des polices web depuis les serveurs de Google.",
        "it": "Carica font web dai server di Google.",
        "pt": "Carrega tipos de letra da web a partir dos servidores da Google.",
        "nl": "Laadt webfonts van de servers van Google.",
        "pl": "Wczytuje fonty internetowe z serwerów Google.",
        "ar": "يحمّل خطوط الويب من خوادم Google.",
        "he": "טוען גופני אינטרנט מהשרתים של Google.",
    },
    "calendly": {
        "fr": "Permet de prendre rendez-vous directement sur la page.",
        "it": "Permette di prenotare appuntamenti direttamente sulla pagina.",
        "pt": "Permite marcar reuniões diretamente na página.",
        "nl": "Laat bezoekers direct op de pagina afspraken maken.",
        "pl": "Umożliwia rezerwację terminów bezpośrednio na stronie.",
        "ar": "يتيح للزوار حجز المواعيد مباشرة على الصفحة.",
        "he": "מאפשר למבקרים לקבוע פגישות ישירות בדף.",
    },
    "hubspot": {
        "fr": "Chat, formulaires et suivi des visiteurs pour notre CRM.",
        "it": "Chat, moduli e monitoraggio dei visitatori per il nostro CRM.",
        "pt": "Chat, formulários e acompanhamento de visitantes para o nosso CRM.",
        "nl": "Chat, formulieren en bezoekerstracking voor ons CRM.",
        "pl": "Czat, formularze i śledzenie odwiedzających dla naszego CRM.",
        "ar": "الدردشة والنماذج وتتبّع الزوار لنظام إدارة علاقات العملاء لدينا.",
        "he": "צ׳אט, טפסים ומעקב מבקרים עבור מערכת ה־CRM שלנו.",
    },
    "intercom": {
        "fr": "Chat en direct et messagerie d’assistance client.",
        "it": "Chat dal vivo e messaggistica per l’assistenza clienti.",
        "pt": "Chat ao vivo e mensagens de apoio ao cliente.",
        "nl": "Livechat en messenger voor klantenservice.",
        "pl": "Czat na żywo i komunikator obsługi klienta.",
        "ar": "دردشة مباشرة وخدمة رسائل لدعم العملاء.",
        "he": "צ׳אט חי ומסנג׳ר לשירות לקוחות.",
    },
    "crisp": {
        "fr": "Widget de chat en direct.",
        "it": "Widget di chat dal vivo.",
        "pt": "Widget de chat ao vivo.",
        "nl": "Livechatwidget.",
        "pl": "Widżet czatu na żywo.",
        "ar": "أداة دردشة مباشرة.",
        "he": "וידג׳ט צ׳אט חי.",
    },
    "google-recaptcha": {
        "fr": "Protège les formulaires contre le spam et les abus.",
        "it": "Protegge i moduli da spam e abusi.",
        "pt": "Protege os formulários contra spam e abusos.",
        "nl": "Beschermt formulieren tegen spam en misbruik.",
        "pl": "Chroni formularze przed spamem i nadużyciami.",
        "ar": "يحمي النماذج من الرسائل المزعجة وإساءة الاستخدام.",
        "he": "מגן על טפסים מפני ספאם ושימוש לרעה.",
    },
}
